{% set name = "prisms-jobs" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prisms-center/prisms_jobs/archive/v{{ version }}.tar.gz
  sha256: 334a69b974eae27862f25080d7e5d22e94f2140a634cc6783b2d4134e2074f02

build:
  entry_points:
    - pstat=prisms_jobs.scripts.pstat:main
    - psub=prisms_jobs.scripts.psub:main
    - taskmaster=prisms_jobs.scripts.taskmaster:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7,<3.12
    - pip
    - six
  run:
    - python >=3.7,<3.12
    - future
    - six

test:
  imports:
    - prisms_jobs
  commands:
    - pip check
    - pstat --help
    - psub --help
    - taskmaster --help
  requires:
    - pip

about:
  home: https://prisms-center.github.io/prisms_jobs_docs/
  summary: A Python package and set of scripts used for submitting and managing cluster jobs via PBS (TORQUE) or Slurm.
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
